from __future__ import annotations

from collections import deque
from dataclasses import dataclass
from typing import Tuple

from permutation_group_schreier import StabilizerChain, group_orbit, identity


@dataclass(frozen=True)
class CanonicalBlockSystemCertificate:
    status: str
    degree: int
    group_orbits: Tuple[Tuple[int, ...], ...]
    minimum_block_size: int
    block_systems: Tuple[Tuple[Tuple[int, ...], ...], ...]
    selected_block_system: Tuple[Tuple[int, ...], ...]
    reason: str


def _gens(group: StabilizerChain):
    return group.original_generators or (identity(group.degree),)


def _group_orbits(group: StabilizerChain):
    unseen = set(range(group.degree))
    out = []
    while unseen:
        x = min(unseen)
        orbit = tuple(sorted(group_orbit(group, x)))
        out.append(orbit)
        unseen -= set(orbit)
    return tuple(sorted(out))


def _pair_orbit(group: StabilizerChain, a: int, b: int):
    seen = {(a, b)}
    q = deque([(a, b)])
    gens = _gens(group)
    while q:
        x, y = q.popleft()
        for g in gens:
            nxt = (g[x], g[y])
            if nxt not in seen:
                seen.add(nxt)
                q.append(nxt)
    return tuple(sorted(seen))


def _components_from_pair_orbit(n: int, orbit):
    adjacency = [set() for _ in range(n)]
    for u, v in orbit:
        adjacency[u].add(v)
        adjacency[v].add(u)
    unseen = set(range(n))
    comps = []
    while unseen:
        root = min(unseen)
        comp = {root}
        q = deque([root])
        unseen.remove(root)
        while q:
            u = q.popleft()
            for v in adjacency[u]:
                if v in unseen:
                    unseen.remove(v)
                    comp.add(v)
                    q.append(v)
        comps.append(tuple(sorted(comp)))
    return tuple(sorted(comps))


def _is_invariant_partition(group: StabilizerChain, partition) -> bool:
    blocks = tuple(tuple(b) for b in partition)
    block_sets = {frozenset(b) for b in blocks}
    return all(
        frozenset(g[u] for u in block) in block_sets
        for g in _gens(group)
        for block in blocks
    )


def canonical_minimal_block_system(group: StabilizerChain) -> CanonicalBlockSystemCertificate:
    """Find canonical intransitive or uniquely minimal transitive block structure.

    For a transitive group, every nontrivial block system containing point 0 is
    generated by some pair (0,b). The orbit of that ordered pair under G defines
    the smallest G-invariant equivalence relation containing 0~b: connect all
    unordered pairs appearing in the pair orbit and take connected components.

    All candidate systems are enumerated as pair-orbit states rather than group
    elements, deduplicated, and audited for generator invariance. The family of
    minimum-block-size systems is canonical. A single member therefore gives a
    canonical block system. Multiple equally minimal systems are returned as a
    canonical family and deliberately left unresolved rather than selecting one
    by numeric labels.
    """
    n = group.degree
    if n < 1:
        raise ValueError("group degree must be positive")
    orbits = _group_orbits(group)
    if len(orbits) > 1:
        return CanonicalBlockSystemCertificate(
            "canonical_intransitive_orbit_partition", n, orbits,
            max(map(len, orbits), default=0), (), orbits,
            "point orbits are a canonical nontrivial invariant partition",
        )
    if n <= 2:
        return CanonicalBlockSystemCertificate(
            "primitive_or_trivial", n, orbits, n, (), (),
            "no nontrivial block system exists at this degree",
        )

    candidates = set()
    for b in range(1, n):
        partition = _components_from_pair_orbit(n, _pair_orbit(group, 0, b))
        if len(partition) <= 1 or any(len(block) <= 1 for block in partition):
            continue
        sizes = {len(block) for block in partition}
        if len(sizes) != 1:
            raise AssertionError("transitive invariant equivalence classes have unequal sizes")
        if not _is_invariant_partition(group, partition):
            raise AssertionError("constructed pair-orbit partition is not G-invariant")
        candidates.add(partition)

    if not candidates:
        return CanonicalBlockSystemCertificate(
            "primitive_or_trivial", n, orbits, n, (), (),
            "no nontrivial pair-generated invariant equivalence relation exists",
        )

    min_size = min(len(p[0]) for p in candidates)
    minimum = tuple(sorted(p for p in candidates if len(p[0]) == min_size))
    if len(minimum) == 1:
        selected = minimum[0]
        return CanonicalBlockSystemCertificate(
            "unique_canonical_minimal_block_system", n, orbits, min_size,
            minimum, selected,
            "the canonical family of minimum-size nontrivial block systems has one member",
        )
    return CanonicalBlockSystemCertificate(
        "multiple_canonical_minimal_block_systems", n, orbits, min_size,
        minimum, (),
        "multiple equally minimal invariant block systems exist; the full canonical family is preserved for the next reduction",
    )
