from itertools import combinations

from johnson_ground_relational_lift_v1 import _standard_subsets
from permutation_group_schreier import schreier_stabilizer_chain
from quasipoly_recurrence_accounting_v3 import validate_quasipoly_recurrence_tree_v3
from signed_johnson_log_design_lemma_si_v3 import signed_johnson_log_design_lemma_si_v3


def _cycle(v):
    return tuple((i + 1) % v for i in range(v))


def _swap01(v):
    p = list(range(v))
    p[0], p[1] = p[1], p[0]
    return tuple(p)


def _induced_symmetric_group(v, k):
    subsets = tuple(combinations(range(v), k))
    index = {S: i for i, S in enumerate(subsets)}

    def induce(sigma):
        return tuple(index[tuple(sorted(sigma[x] for x in S))] for S in subsets)

    return schreier_stabilizer_chain([induce(_swap01(v)), induce(_cycle(v))])


def _affine_plane_lines_order3():
    points = tuple((a, b) for a in range(3) for b in range(3))
    index = {p: i for i, p in enumerate(points)}
    directions = ((1, 0), (0, 1), (1, 1), (1, 2))
    lines = set()
    for dx, dy in directions:
        for x, y in points:
            lines.add(tuple(sorted(index[((x + s * dx) % 3, (y + s * dy) % 3)] for s in range(3))))
    assert len(lines) == 12
    return frozenset(lines)


def _affine_line_containing_four_set_string():
    # On J(9,4), color a 4-set iff it contains one affine-plane line.  The
    # canonical t=3 relation generated by H5 has exactly two classes: the 12
    # affine lines and the 72 non-lines.  The line class is a 2-(9,3,1) design,
    # so point incidence and pair codegrees are homogeneous even though the
    # relation has large exact symmetry defect.  This is a real homogeneous H6
    # Design fixture rather than a hand-injected DesignLemmaCandidateSI.
    lines = _affine_plane_lines_order3()
    subsets = tuple(combinations(range(9), 4))
    return tuple(int(any(set(line).issubset(S) for line in lines)) for S in subsets)


def test_rev213_preserves_delegated_h5_exact_path_without_reaccounting_it_as_design():
    v, k = 6, 3
    group = _induced_symmetric_group(v, k)
    subsets = _standard_subsets(v, k)
    source = tuple(int(0 in S) for S in subsets)
    got = signed_johnson_log_design_lemma_si_v3(
        group,
        source,
        source,
        root_n=64,
        max_test_sets=1000,
        max_partition_states=256,
        max_candidate_group_order=256,
    )
    if got.h6_result.h5_result.exact and got.h6_result.h5_result.local_cost_certified:
        assert got.cost_certified and got.proof is got.h6_result.h5_result
        assert got.execution_accounting is None
        assert validate_quasipoly_recurrence_tree_v3(got.proof.accounting).certified
    else:
        # The wrapper must not manufacture a Design proof when H5 merely returns a
        # structural filter under a deliberately bounded candidate recursion.
        assert not got.cost_certified and got.proof is None
        assert got.execution_accounting is None


def test_rev213_affine_plane_homogeneous_design_path_becomes_cost_certified_only_after_full_exact_execution():
    v, k = 9, 4
    group = _induced_symmetric_group(v, k)
    source = _affine_line_containing_four_set_string()
    got = signed_johnson_log_design_lemma_si_v3(
        group,
        source,
        source,
        root_n=group.degree,
        max_test_sets=1000,
        max_partition_states=2000,
        max_design_states=200000,
        max_design_wl_rounds=256,
        max_design_branch_pairs=200000,
        max_candidate_group_order=1024,
        max_depth=64,
    )

    assert got.h6_result.h5_result.status == "undetermined_log_certificate_design_gate"
    assert got.h6_result.design_result is not None
    if got.h6_result.exact:
        # Exact finite set reconstruction is still insufficient by itself.  The
        # rev213 success assertion requires the independently composed rev212 cost
        # certificate and final recurrence verifier as well.
        assert got.cost_certified, got.reason
        assert got.proof is not None and got.execution_accounting is not None
        assert got.execution_accounting.certified
        assert validate_quasipoly_recurrence_tree_v3(got.proof.accounting).certified
    else:
        # Resource/theorem incompleteness stays typed fail-closed. This branch is
        # intentionally accepted by the regression because the purpose is also to
        # guarantee that rev213 never converts a nonexact Design attempt into a
        # complexity-certified solve under CI resource limits.
        assert not got.cost_certified and got.proof is None
        assert got.status == "undetermined_w1r_h6_design_execution"


def test_rev213_homogeneous_constant_relation_still_fails_the_symmetry_defect_gate():
    v, k = 6, 3
    group = _induced_symmetric_group(v, k)
    source = tuple(0 for _ in _standard_subsets(v, k))
    got = signed_johnson_log_design_lemma_si_v3(
        group,
        source,
        source,
        root_n=64,
        max_test_sets=1000,
        max_partition_states=256,
        max_design_wl_rounds=64,
        max_candidate_group_order=256,
        max_depth=1,
    )
    assert not got.cost_certified and got.proof is None
    assert got.h6_result.design_result is not None
    assert not got.h6_result.design_result.theorem_hypotheses_certified
